getmaxun/maxun

LICENSE, README.md
=> chore: license

maxun-core/src/utils/concurrency.ts
=> chore: update concurrency.ts

server/src/api/record.ts, server/src/workflow-management/scheduler/index.ts, src/apiConfig.js
reported by a lot of users on discord.
=> fix: handle `undefined` backend url in local setup

src/components/organisms/RightSidePanel.tsx
=> feat: handle capture list initial capture stage confirmation

server/src/routes/auth.ts
=> chore: remove debug print for req.body

src/components/molecules/RunContent.tsx
make it match the style of Download as JSON
=> fix: download as csv button style

server/src/browser-management/classes/RemoteBrowser.ts
Browser viewport during robot interpretation fixed.
=> fix: remote browser rendering

server/src/storage/mino.ts
remove the "bucket does not exist" message for test bucket
=> chore: minio success message

server/src/middlewares/auth.ts, server/src/routes/auth.ts, server/src/routes/storage.ts, src/api/storage.ts, src/components/molecules/RecordingsTable.tsx, src/components/molecules/RobotDuplicate.tsx, src/components/molecules/RobotEdit.tsx, src/components/organisms/Recordings.tsx, src/context/auth.tsx, src/index.css
Robot duplication feature added. Let's you duplicate robots.
fix #152 
https://github.com/user-attachments/assets/ef75826d-90aa-4275-b169-58879254ccc2
=> feat: robot duplication

src/pages/Login.tsx, src/pages/Register.tsx
Improving login and register forms
=> feat: register and login forms redesign

src/components/molecules/RobotSettings.tsx
Robot limit field added to robot settings modal
=> feat: display robot limit in robot settings

package.json, server/src/api/record.ts, server/src/browser-management/classes/RemoteBrowser.ts, server/src/routes/proxy.ts, server/src/routes/record.ts, server/src/routes/storage.ts, server/src/workflow-management/scheduler/index.ts
captcha will be added in next release - need to check out alternatives.
=> feat: bring back oss steath mode 🥷

.dockerignore, docker-compose.yml, server/Dockerfile
=> feat: publish docker image

src/components/molecules/RobotDuplicate.tsx, src/components/molecules/RobotEdit.tsx
1. Add one second timeout to display notification before reloading for Robot Edit and Robot Duplication.
=> feat: add notification timeout

src/components/molecules/RobotEdit.tsx
Edit robot limit set to be greater than or equal to 1.
fix #200
=> fix: min edit robot limit set to be 1

src/components/molecules/RecordingsTable.tsx
=> feat: rearrange robot options

src/components/molecules/InterpretationButtons.tsx
to avoid confusion or feel "stuck", made some changes
=> feat: enhance output preview load

.github/.github/COMMIT_CONVENTION.md, .github/CODE_OF_CONDUCT.md, README.md
1. Code of Conduct
2. Contributing
3. Commit Convention
=> chore: add `.github` files

src/context/auth.tsx
=> feat: auto logout

src/components/browser/BrowserRecordingSave.tsx, src/components/recorder/SaveRecording.tsx
match rounded corners. Was available prior to dark theme.
=> feat: recorder save panel UI consistency 

server/src/browser-management/classes/BrowserPool.ts, server/src/browser-management/controller.ts, server/src/routes/record.ts, server/src/workflow-management/classes/Interpreter.ts, src/pages/MainPage.tsx
=> Revert "fix: prevent page reload on run trigger to open remote browser"

server/src/server.ts, server/src/worker.ts
=> fix: Run status displays failed on system termination

src/components/browser/BrowserWindow.tsx, src/components/recorder/RightSidePanel.tsx
What this PR does? 
Generates truly unique id value for action ids using uuid.
=> feat: generate truly unique action ids
